api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Document']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    doctrine:
        # To enable or disable Doctrine ORM support.
        enabled: false
    doctrine_mongodb_odm:
        # To enable or disable Doctrine MongoDB ODM support.
        enabled: true

    eager_loading:
        # To enable or disable eager loading.
        enabled: true
